test:
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  cache:
    paths:
      - "$CI_PROJECT_DIR/pip-cache"
    key: "$CI_PROJECT_ID"
  tags:
    - docker
  image: python:3.6
  before_script:
    - pip install tox
    - pip install git+https://gitlab-ci-token:${CI_JOB_TOKEN}@mad-srv.informatik.uni-erlangen.de/MadLab/GaitAnalysis/sensorcalibration.git
  script:
    - tox
